# GENERAL
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[shell]
program = "zsh"
args = ["--login"]
# args = ["--login", "-c", "tmux new-session -A -s home"]

# ENV
[env]
TERM = "xterm-256color"

# WINDOW
[window]
opacity = 0.85
decorations = "None"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
padding = { x = 5, y = 5 }
dimensions = { columns = 0, lines = 0}

# SCROLLING
[scrolling]
history = 30000
multiplier = 3

# FONT
[font]
size = 16.0
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
glyph_offset = { x = 0, y = 0}
offset = { x = 0, y = 0}

# COLORS
[colors]
draw_bold_text_with_bright_colors = true

# SELECTION
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>t"

# CURSOR
[cursor]
style = "Block"
unfocused_hollow = true

# MOUSE
[mouse]
hide_when_typing = true
bindings = [
  {mouse = "Middle", mods = "Control", action = "PasteSelection"}
]

# HINTS
[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
mouse = { mods = "Control|Shift", enabled = true }

# KEYBOARD
[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "alacritty -e 'htop' & \r"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "alacritty -e 'ipython' & \r"
key = "I"
mods = "Command|Shift"

# DEBUG
[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false
